---
title: "Lab 6 - 12 Days of Christmas"
author: "Kirina Sirohi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
library(english)
```

```{r importing dataset}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

```{r pluralize_gift}
pluralize_gift <- function(gift){

gift <- gift %>% 
  str_replace("y$", "ie") %>% 
  paste("s", sep = "") %>% 
  str_replace_all("ss$", "s") %>% 
  str_replace("ooses$", "eese")

  return(gift)

}
```

```{r creating sentences}
make_phrase <- function(num, num_word, item, verb, adjective, location) {
  
  verb <- replace_na(verb, "")
  item <- replace_na(item, "")
  adjective <- replace_na(adjective, "")
  location <- replace_na(location, "")
  
  
  a_and_an <- str_sub(item, 1, 1) %>% 
    str_detect("[aeiou]")
  
  if (num > 1) {
    item <- pluralize_gift(item)
  } else if (a_and_an == TRUE) {
    num_word <- "an"
  } else {
    num_word <- "a"
  }
  
  
  glue("{num_word} {adjective} {item} {verb} {location}") %>% 
    str_trim("both")
  
  
}


xmas <- xmas %>%
  mutate(
    num_word = as.character(english(Day)),
    Full.Phrase = pmap_chr(list(Day, num_word, Gift.Item, Verb, Adjective, Location), make_phrase) %>% 
      str_replace_all("  ", " ")
  )
```


```{r iteration}
sing_day <- function(dataset, line, phrase_col){
  
  phrases <- dataset %>% pull({{phrase_col}})
  
  line_as_word <- ordinal(line)
  beginning <- glue("On the {line_as_word} day of Christmas, my true love gave to me,")
  

  phrases[1] <- paste("and", phrases[1], ".")
  phrase_lines <- str_c(phrases[line:1], collapse = ", \n")

  
  glue("{beginning} \n{phrase_lines}")

  
}
```

# Unit Testing

```{r unit testing}
library(testthat)
library(usethis)
```


```{r pluralize gift}
test_that("pluralize_gift works", {
  expect_match(pluralize_gift("Jello"), "Jellos")
})
```

```{r pluralize gift}
test_that("pluralize_gift works", {
  expect_match(pluralize_gift("curtain"), "curtains")
})
```

```{r}
test_that("make_phrase", {
  expect_match(make_phrase(12, "twelve", "giants", "jelloing", "", ""), "twelve  giants jelloing")
})
```

```{r}
test_that("make_phrase", {
  expect_match(make_phrase(6, "six", "monkeys", "galloping", "", ""), "six  monkeys galloping")
})
```

``` {r}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

```{r sing_day}
test_that("sing_day", {
  expect_match(sing_day(xmas, 2, Adjective), "On the second day of Christmas, my true love gave to me, \nturtle, \nand NA .")

})
```

```{r sing_day}
test_that("sing_day", {
  expect_match(sing_day(xmas, 5, Gift.Item), "On the fifth day of Christmas, my true love gave to me, 
ring, 
bird, 
hen, 
dove, 
and partridge .")

})
```

